### ISSUE TITLE
Add screenshots in readme

### ISSUE THREAD

**Issue by Devansh-Baghel** [Devansh-Baghel/book-store#1]
Take screenshots of the cart page, home page and store page from [here](https://book-store-odin.vercel.app/) and add them to readme.

**Comment by CoderRedwing** [comment]
can i work on it

**Comment by Devansh-Baghel** [comment]
@CoderRedwing assigned!

**Comment by CoderRedwing** [comment]
please check the pr if it is okay then kindly accept the pr
